roc_is_metrics = [
    "Tax Effect Of Unusual Items",
    "Tax Rate For Calcs",
    "Total Unusual Items",
    "Total Unusual Items Excluding Goodwill",
    "Net Income From Continuing Operation Net Minority Interest",
    "Reconciled Depreciation",
    "Net Interest Income",
    "Interest Expense",
    "Interest Income",
    "Normalized Income",
    "Net Income From Continuing And Discontinued Operation",
    "Diluted Average Shares",
    "Basic Average Shares",
    "Diluted EPS",
    "Basic EPS",
    "Diluted NI Availto Com Stockholders",
    "Average Dilution Earnings",
    "Net Income Common Stockholders",
    "Net Income",
    "Minority Interests",
    "Net Income Including Noncontrolling Interests",
    "Net Income Discontinuous Operations",
    "Net Income Continuous Operations",
    "Tax Provision",
    "Pretax Income",
    "Other Non Operating Income Expenses",
    "Special Income Charges",
    "Other Special Charges",
    "Write Off",
    "Impairment Of Capital Assets",
    "Restructuring And Mergern Acquisition",
    "Gain On Sale Of Security",
    "Operating Expense",
    "Other Operating Expenses",
    "Depreciation Amortization Depletion Income Statement",
    "Depreciation And Amortization In Income Statement",
    "Amortization",
    "Amortization Of Intangibles Income Statement",
    "Depreciation Income Statement",
    "Selling General And Administration",
    "Selling And Marketing Expense",
    "General And Administrative Expense",
    "Other Gand A",
    "Insurance And Claims",
    "Rent And Landing Fees",
    "Salaries And Wages",
    "Total Revenue",
    "Operating Revenue",
    "Occupancy And Equipment",
    "Other Non Interest Expense",
    "Normalized EBITDA",
    "Reconciled Cost Of Revenue",
    "EBITDA",
    "EBIT",
    "Total Expenses",
    "Rent Expense Supplemental",
    "Total Operating Income As Reported",
    "Other Income Expense",
    "Gain On Sale Of Business",
    "Earnings From Equity Interest",
    "Net Non Operating Interest Income Expense",
    "Total Other Finance Cost",
    "Interest Expense Non Operating",
    "Interest Income Non Operating",
    "Operating Income",
    "Gross Profit",
    "Cost Of Revenue",
    "Earnings From Equity Interest Net Of Tax",
    "Gain On Sale Of Ppe",
    "Securities Amortization",
    "Research And Development",
    "Otherunder Preferred Stock Dividend",
    "Preferred Stock Dividends",
    "Professional Expense And Contract Services Expense",
    "Provision For Doubtful Accounts",
    "Loss Adjustment Expense",
    "Net Policyholder Benefits And Claims",
    "Policyholder Benefits Gross",
    "Policyholder Benefits Ceded",
    "Other Taxes"
]

roc_bs_metrics = [
    "Treasury Shares Number",
    "Ordinary Shares Number",
    "Share Issued",
    "Net Debt",
    "Total Debt",
    "Tangible Book Value",
    "Invested Capital",
    "Net Tangible Assets",
    "Common Stock Equity",
    "Total Capitalization","Total Equity Gross Minority Interest","Minority Interest","Stockholders Equity","Gains Losses Not Affecting Retained Earnings","Other Equity Adjustments","Fixed Assets Revaluation Reserve","Foreign Currency Translation Adjustments","Treasury Stock","Retained Earnings","Capital Stock","Common Stock","Total Liabilities Net Minority Interest","Derivative Product Liabilities","Employee Benefits","Non Current Pension And Other Postretirement Benefit Plans","Long Term Debt And Capital Lease Obligation","Long Term Debt","Current Deferred Liabilities","Current Deferred Taxes Liabilities","Current Debt And Capital Lease Obligation","Current Notes Payable","Current Debt","Current Provisions","Payables And Accrued Expenses","Payables","Other Payable","Dividends Payable","Total Tax Payable","Accounts Payable","Total Assets","Defined Pension Benefit","Investments And Advances","Investmentin Financial Assets","Available For Sale Securities","Financial Assets Designatedas Fair Value Through Profitor Loss Total","Trading Securities","Long Term Equity Investment","Investments In Other Ventures Under Equity Method","Investmentsin Associatesat Cost","Goodwill And Other Intangible Assets","Other Intangible Assets","Goodwill","Net PPE","Accumulated Depreciation","Gross PPE","Leases","Other Properties","Machinery Furniture Equipment","Buildings And Improvements","Land And Improvements","Prepaid Assets","Receivables","Taxes Receivable","Other Short Term Investments","Cash And Cash Equivalents","Cash Financial","Cash Cash Equivalents And Federal Funds Sold","Working Capital","Capital Lease Obligations","Other Equity Interest","Unrealized Gain Loss","Additional Paid In Capital","Total Non Current Liabilities Net Minority Interest","Other Non Current Liabilities","Tradeand Other Payables Non Current","Non Current Deferred Liabilities","Non Current Deferred Revenue","Non Current Deferred Taxes Liabilities","Long Term Capital Lease Obligation","Long Term Provisions","Current Liabilities","Other Current Liabilities","Current Deferred Revenue","Current Capital Lease Obligation","Line Of Credit","Total Non Current Assets","Other Non Current Assets","Non Current Deferred Assets","Non Current Deferred Taxes Assets","Non Current Accounts Receivable","Financial Assets","Investmentsin Joint Venturesat Cost","Construction In Progress","Current Assets","Other Current Assets","Hedging Assets Current","Assets Held For Sale Current","Current Deferred Assets","Current Deferred Taxes Assets","Restricted Cash","Inventory","Accounts Receivable","Cash Cash Equivalents And Short Term Investments","Cash Equivalents","Non Current Accrued Expenses","Dueto Related Parties Non Current","Pensionand Other Post Retirement Benefit Plans Current","Current Accrued Expenses","Dueto Related Parties Current","Non Current Prepaid Assets","Duefrom Related Parties Non Current","Non Current Note Receivables","Other Investments","Properties","Other Receivables","Duefrom Related Parties Current","Loans Receivable","Allowance For Doubtful Accounts Receivable","Gross Accounts Receivable","Finished Goods","Work In Process","Raw Materials","Receivables Adjustments Allowances","Preferred Stock Equity","Preferred Stock","Preferred Securities Outside Stock Equity","Commercial Paper","Income Tax Payable","Held To Maturity Securities","Interest Payable","Other Inventories","Investment Properties","Accrued Interest Receivable","Inventories Adjustments Allowances","Other Capital Stock","Investmentsin Subsidiariesat Cost"
]

financial_ratio_tuples = [
    ("Total Revenue", "avg Total Assets", "Total Asset Turnover"),
    ("Net Income Common Stockholders", "avg Common Stock Equity", "ROE"),
    ("Net Income Common Stockholders", "avg Total Assets", "ROA"),
    ("Net Income Common Stockholders", "avg Invested Capital", "ROIC"),
    ("Net Income Common Stockholders", "Total Revenue", "Net Income Margin"),
    ("Operating Income", "Total Revenue", "Operating Profit Margin"),
    ("EBITDA", "Total Revenue", "EBITDA Margin"),
    ("EBIT", "Total Revenue", "EBIT Margin"),
    ("Gross Profit", "Total Revenue", "Gross Profit Margin"),
    ("Interest Expense", "avg Total Debt", "Average Interest Rate"),
    ("Cash And Cash Equivalents", "avg Total Assets", "Cash/Assets Ratio"),
    ("Total Debt", "Total Assets", "Total Debt/Assets ratio"),
    ("Net Debt", "Total Assets", "Net Debt/Assets ratio"),
    # ("Net Income", "avg Total Liabilities Net Minority Interest", "Return on Liabilities"),
    # ("Net Income", "avg Total Equity Gross Minority Interest", "Return on Equity"),
    # ("Net Income", "avg Total Liabilities Net Minority Interest", "Return on Liabilities"),
    # ("Net Income", "avg Total Equity Gross Minority Interest", "Return on Equity"),
    # ("Net Income", "avg Total Liabilities Net Minority Interest", "Return on Liabilities"),
    # ("Net Income", "avg Total Equity Gross Minority Interest", "Return on Equity"),
    # ("Net Income", "avg Total Liabilities Net Minority Interest", "Return on Liabilities"),

]